import { SEOOpportunity, GenericAction, PlatformConnector } from './types';
import { LLMProvider } from '../tools/llm';

import { z } from 'zod';

export class ExecutionEngine {
  private connector: PlatformConnector;

  constructor(connector: PlatformConnector) {
    this.connector = connector;
  }

  // Translates an approved opportunity into a specific generic action using the LLM
  async planAction(opportunity: SEOOpportunity, pageUrl: string): Promise<GenericAction> {
    const context = `
      You are an execution agent. An SEO opportunity has been approved by the user.
      
      Problem: ${opportunity.problem}
      Recommended Action: ${opportunity.recommended_action}
      Target URL: ${pageUrl}
      
      Determine the precise generic action required to implement this.
    `;

    try {
      const { object } = await LLMProvider.generateObject({
      agent: 'Executor',
      
        
        schema: z.object({
          type: z.enum([
            'update_title', 'update_meta_description', 'update_content', 
            'add_internal_link', 'create_content', 'create_schema', 
            'update_robots_txt', 'update_canonical'
          ]),
          target_url: z.string(),
          payload: z.record(z.string(), z.any())
        }),
        prompt: context,
        system: "You translate human-readable recommendations into strict generic actions for the execution layer."
      });

      return object as GenericAction;
    } catch (error) {
      console.error('Failed to plan action:', error);
      throw error;
    }
  }

  // Orchestrates the execution of a generic action
  async execute(action: GenericAction): Promise<{ pr_url: string, pr_number: number }> {
    
    // 1. Ask connector to translate the generic action into specific file diffs
    const changes = await this.connector.translate_action_to_diff(action);

    if (!changes || changes.length === 0) {
      throw new Error("Connector could not generate diffs for this action.");
    }

    // 2. Generate branch name and PR details
    const branchName = `seo-bot/${action.type}-${Date.now()}`;
    const prTitle = `SEO: Automated ${action.type.replace(/_/g, ' ')}`;
    const prBody = `
## Autonomous SEO Execution

This PR was automatically generated by the Autonomous AI SEO Agent.

**Action:** ${action.type}
**Target URL:** ${action.target_url}

Please review the proposed changes carefully before merging.
    `;

    // 3. Execute via connector (creates branch, commits, opens PR)
    const prDetails = await this.connector.execute_changes(
      branchName,
      changes.map(c => ({ file_path: c.file_path, new_content: c.diff_after })),
      prTitle,
      prBody
    );

    return prDetails;
  }
}
